seed: 0
t0: 0.0
t_final: 2.0
x0: 1.0
params:
  a: 1.0
expr: "a * x"  # dx/dt = a*x default
grid:
  t_min: 0.0
  t_max: 2.0
  x_min: -2.0
  x_max: 4.0
  n_t: 25
  n_x: 25
isocline_levels: [-2, -1, 0, 1, 2]
dt_list: [0.4, 0.2, 0.1, 0.05, 0.025]
dt_ref: 0.001
output_parquet: "results.parquet"
fig_dir: "figs"
