seed: 42
polynomial:
  coeffs:
  - 1
  - -6
  - 11
  - -6
  method: companion
  tol: 1.0e-12
  max_iter: 200
viz:
  real_curve:
    x_min: 0
    x_max: 4
    num: 1000
    root_tol: 1.0e-08
  complex_map: {}
  synthetic_division_r: 1.0
io:
  results_parquet: results.parquet
  results_csv: results.csv
  fig_dir: figs
  real_curve_png: figs/real_curve.png
  complex_map_png: figs/complex_roots.png
