seed: 42
t_span:
- 0.0
- 160.0
dt: 0.5
model_type: SIR
population: 1000000
initial_conditions:
  S0: 999000
  E0: 0
  I0: 1000
  R0: 0
params:
  beta: 0.3
  gamma: 0.1
  sigma: 0.2
beta_schedule:
- - 0.0
  - 0.3
- - 40.0
  - 0.22
- - 80.0
  - 0.16
- - 120.0
  - 0.2
monte_carlo:
  n_samples: 200
  beta_gsd: 1.25
  gamma_gsd: 1.2
  sigma_gsd: 1.2
  I0_gsd: 1.3
output:
  results_parquet: results.parquet
  mc_parquet: results_mc.parquet
