seed: 42
t_final: 10.0
dt: 0.01
true_params:
  theta1: 9.81
  theta2: 0.15
x0:
- 0.8
- 0.0
obs:
  noise_std: 0.05
  observe: x1
estimation:
  initial_guess:
    theta1: 7.0
    theta2: 0.3
  prior:
    mu:
    - 9.81
    - 0.2
    Sigma:
    - - 1.0
      - 0.0
    - - 0.0
      - 0.01
    use_prior: true
  spline_smoothing: 0.001
paths:
  results_parquet: /mnt/data/parameter_id_ode_portfolio/results.parquet
  figs_dir: /mnt/data/parameter_id_ode_portfolio/figs
  results_csv: /mnt/data/parameter_id_ode_portfolio/results.csv
