seed: 0
view: [-1.0, 5.0, -1.0, 5.0]   # [xmin, xmax, ymin, ymax]
heatmap_grid_n: 200
tolerance: 1.0e-9
bounding_box: null            # or [xmin, xmax, ymin, ymax]
inequalities:
  - {a: [1.0, 0.0], b: 0.0, sense: ">="}   # x >= 0
  - {a: [0.0, 1.0], b: 0.0, sense: ">="}   # y >= 0
  - {a: [1.0, 1.0], b: 4.0, sense: "<="}   # x + y <= 4
