seed: 42
n: 1000
epsilon_grid:
- 0.0
- 0.02
- 0.05
- 0.1
- 0.15
- 0.2
- 0.3
base_dist:
  name: normal
  mu: 0.0
  sigma: 1.0
out_dist:
  name: normal
  mu: 6.0
  sigma: 1.0
z_params:
  tau: 3.0
z_robust_params:
  tau: 3.5
  mad_eps: 1.0e-09
iqr_params:
  k: 1.5
sample_for_plot:
  epsilon: 0.15
