A:
- - 0.0
  - 1.0
- - -2.0
  - -1.0
dt: 0.02
initial_conditions:
- - 1.0
  - 0.0
- - 0.5
  - 0.5
- - -1.0
  - 1.0
- - 2.0
  - -1.0
integrator:
  atol: 1.0e-12
  method: RK45
  rtol: 1.0e-09
output:
  fig_dir: figs
  results_path: results.parquet
seed: 42
t_final: 10.0
