seed: 0
output_dir: "artifacts"
record_steps: true

# Default polygon: unit square
polygon:
  vertices:
    - [0.0, 0.0]
    - [1.0, 0.0]
    - [1.0, 1.0]
    - [0.0, 1.0]

# Transformation pipeline (edit freely)
ops:
  - type: rotate
    theta: 0.78539816339      # pi/4
    center: [0.5, 0.5]        # rotate around polygon centroid-ish
  - type: translate
    tx: 1.0
    ty: 0.2
  - type: reflect
    # reflect across a line with angle phi (line through origin)
    angle: 0.0                # 0 → reflect across x-axis if we choose normal = (0,1)
    normal: null              # optional override; if null use angle
    point: null               # optional point (cx, cy) for off-origin reflection
